Fix formatting

diff --git a/.github/workflows/auto_build_on_upstream_release.yml b/.github/workflows/auto_build_on_upstream_release.yml
--- a/.github/workflows/auto_build_on_upstream_release.yml
+++ b/.github/workflows/auto_build_on_upstream_release.yml
@@ -102,18 +102,18 @@ jobs:
         env:
           TAG: ${{ needs.check-upstream.outputs.tag }}
         run: |
-        LATEST_TAG=$(gh api /repos/simplyprint/printer-prusa-firmware/releases/latest | jq .tag_name)
-        if [ ! "$LATEST_TAG" ]; then
-          echo "::error::Latest tag not found, exiting"
-          exit 1
-        fi
-        
-        echo "Upgrading patches from $LATEST_TAG to $TAG"
+          LATEST_TAG=$(gh api /repos/simplyprint/printer-prusa-firmware/releases/latest | jq .tag_name)
+          if [ -z "$LATEST_TAG" ] || [ "$LATEST_TAG" = "null" ]; then
+            echo "::error::Latest tag not found, exiting"
+            exit 1
+          fi
 
-        ./upgrade_version.sh "$TAG" "$LATEST_TAG" 2>&1 | tee patches.log
-        echo "patches_log=$(cat patches.log)" >> "$GITHUB_OUTPUT"
+          echo "Upgrading patches from $LATEST_TAG to $TAG"
 
-        ./make_patches.sh "$TAG"
+          ./upgrade_version.sh "$TAG" "$LATEST_TAG" 2>&1 | tee patches.log
+          echo "patches_log=$(cat patches.log)" >> "$GITHUB_OUTPUT"
+
+          ./make_patches.sh "$TAG"
 
       - name: Create pull request for patches
         uses: peter-evans/create-pull-request@v8
@@ -132,21 +132,21 @@ jobs:
           PRESETS: ${{ needs.check-upstream.outputs.presets }}
           COMMIT: ${{ github.sha }}
         run: |
-        rm -rf build/
-        mkdir -p /tmp/firmware-out
-        
-        export PRUSA_FIRMWARE_BUDDY_DIR_NAME="Prusa-Firmware-Buddy-DEV"
-        ./scripts/build_local.sh "$TAG" "$PRESETS" ON
+          rm -rf build/
+          mkdir -p /tmp/firmware-out
 
-        for firmware in build/*/firmware.bbf; do
-          parent_dir=$(basename $(dirname "$firmware"))
-          if [ "$parent_dir" = "products" ]; then
-            continue
-          fi
-          preset="${parent_dir%_release_boot}"
-          new_name="sp_prusa_${preset}_${TAG}+${COMMIT}@$(date +%d-%m-%Y).bbf"
-          mv "$firmware" "/tmp/firmware-out/$new_name"
-        done
+          export PRUSA_FIRMWARE_BUDDY_DIR_NAME="Prusa-Firmware-Buddy-DEV"
+          ./scripts/build_local.sh "$TAG" "$PRESETS" ON
+
+          for firmware in build/*/firmware.bbf; do
+            parent_dir=$(basename $(dirname "$firmware"))
+            if [ "$parent_dir" = "products" ]; then
+              continue
+            fi
+            preset="${parent_dir%_release_boot}"
+            new_name="sp_prusa_${preset}_${TAG}+${COMMIT}@$(date +%d-%m-%Y).bbf"
+            mv "$firmware" "/tmp/firmware-out/$new_name"
+          done
 
       - name: Create draft release and upload binaries
         env:
